# Generated by Django 2.2.5 on 2019-09-26 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sehir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('il', models.CharField(max_length=100)),
                ('ilce', models.CharField(max_length=100)),
                ('ilResim', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AltSehir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yerAdi', models.CharField(max_length=100)),
                ('geziTür', models.CharField(max_length=100)),
                ('konumX', models.FloatField()),
                ('konumY', models.FloatField()),
                ('sehir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Sehir')),
            ],
        ),
    ]
