# Generated by Django 3.0.3 on 2020-03-27 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurantlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurantAdi', models.CharField(max_length=100)),
                ('restaurantYildiz', models.CharField(max_length=10)),
                ('konumX', models.FloatField()),
                ('konumY', models.FloatField()),
                ('sehir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Sehir')),
            ],
        ),
        migrations.CreateModel(
            name='Oteller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otelAdi', models.CharField(max_length=100)),
                ('otelYildiz', models.CharField(max_length=10)),
                ('konumX', models.FloatField()),
                ('konumY', models.FloatField()),
                ('sehir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Sehir')),
            ],
        ),
    ]
